# Generated by Django 4.2.2 on 2023-08-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_address_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=6, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing',
            field=models.BooleanField(default=False, verbose_name='marketing'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal',
            field=models.BooleanField(default=False, verbose_name='personal'),
        ),
    ]
