# Generated by Django 4.2.2 on 2023-08-28 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='payment_id')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='price')),
                ('describtion', models.TextField(blank=True, verbose_name='describtion')),
                ('pgi', models.CharField(choices=[('zarrin', 'zarrin'), ('idpay', 'idpay')], max_length=20, verbose_name='gateway interface (pgi)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is_paid')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_order', to='order.order', verbose_name='order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment',
            },
        ),
    ]
