# Generated by Django 4.2.2 on 2023-08-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-updated'], 'verbose_name': 'Faq', 'verbose_name_plural': 'Faq'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['-updated'], 'verbose_name': 'Rule', 'verbose_name_plural': 'Rule'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ['-updated'], 'verbose_name': 'UserMessage', 'verbose_name_plural': 'UserMessage'},
        ),
    ]
