# Generated by Django 4.2.2 on 2023-08-21 17:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_faq_options_alter_rule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=ckeditor.fields.RichTextField(verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule',
            field=ckeditor.fields.RichTextField(verbose_name='rules'),
        ),
    ]
