# Generated by Django 4.2.2 on 2023-08-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_alter_ticketsold_cart'),
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ticket',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart_tickets', to='ticket.ticket', verbose_name='ticket'),
        ),
    ]
