# Generated by Django 4.2.2 on 2023-07-10 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ticket.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('ticket_number', models.CharField(blank=True, max_length=20, verbose_name='ticket_number')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='price')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='discount')),
                ('number_sold', models.PositiveIntegerField(default=0, verbose_name='number_sold')),
                ('is_acive', models.BooleanField(default=True, verbose_name='is_active')),
                ('image', models.ImageField(blank=True, null=True, upload_to=ticket.models.ticket_image_path, verbose_name='image')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('slug', models.SlugField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Ticket',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='TicketSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(blank=True, max_length=10, verbose_name='ticket_code')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('is_paid', models.BooleanField(default=True, verbose_name='is_paid')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('slug', models.SlugField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketsold_cart', to='cart.cart', verbose_name='cart')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketsold_ticket', to='ticket.ticket', verbose_name='ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketsold_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'TicketSold',
                'verbose_name_plural': 'TicketSold',
                'ordering': ['-updated'],
            },
        ),
    ]
