# Generated by Django 4.2.2 on 2023-07-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketsold',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
