# Generated by Django 4.2.2 on 2023-07-12 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='lottery_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='lottery date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketsold',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketsold_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
