# Generated by Django 4.2.2 on 2023-08-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_lottery_date_alter_ticketsold_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='prize_value',
            field=models.DecimalField(decimal_places=0, default=5000000, max_digits=12, verbose_name='prize_value'),
        ),
    ]
