# Generated by Django 4.2.2 on 2023-08-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_name_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='prize_value',
            field=models.DecimalField(decimal_places=0, default=1000000, max_digits=12, verbose_name='prize_value'),
        ),
    ]
