# Generated by Django 4.2.2 on 2023-08-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_prize_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='is_acive',
            new_name='is_active',
        ),
    ]
