# Generated by Django 4.2.2 on 2023-08-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_rename_is_acive_ticket_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsold',
            name='status',
            field=models.CharField(choices=[('win', 'win'), ('pending', 'pending'), ('lose', 'lose')], default='pending', max_length=10, verbose_name='status'),
        ),
    ]
