# Generated by Django 4.2.2 on 2023-08-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticketsold_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_ended',
            field=models.BooleanField(default=False, verbose_name='is_ended'),
        ),
    ]
