# Generated by Django 4.2.2 on 2023-08-21 17:33

from django.db import migrations
import sorl.thumbnail.fields
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticket_is_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=ticket.models.ticket_image_path, verbose_name='image'),
        ),
    ]
