# Generated by Django 4.2.2 on 2023-08-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsold',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='is_paid'),
        ),
    ]
