# Generated by Django 4.2.2 on 2023-08-21 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_ticket'),
        ('ticket', '0008_alter_ticketsold_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsold',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketsold_order', to='order.order', verbose_name='order'),
        ),
    ]
