# Generated by Django 4.2.2 on 2023-08-21 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('ticket', '0009_ticketsold_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsold',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketsold_cart', to='cart.cart', verbose_name='cart'),
        ),
    ]
