# Generated by Django 4.2.2 on 2023-08-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticketsold_is_paid'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.ManyToManyField(related_name='order_ticket', to='ticket.ticket', verbose_name='ticket'),
        ),
    ]
